/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProfileIdRouteImport } from './routes/profile.$id'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as PaymentReturnRouteImport } from './routes/payment.return'
import { Route as OrderIdRouteImport } from './routes/order.$id'
import { Route as CheckoutIdRouteImport } from './routes/checkout.$id'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSystemWalletsRouteImport } from './routes/admin.system-wallets'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminPayoutsRouteImport } from './routes/admin.payouts'
import { Route as AdminFeaturesRouteImport } from './routes/admin.features'
import { Route as AdminCoursesRouteImport } from './routes/admin.courses'
import { Route as AdminCommunicationsRouteImport } from './routes/admin.communications'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminCampaignsRouteImport } from './routes/admin.campaigns'
import { Route as AdminBountiesRouteImport } from './routes/admin.bounties'
import { Route as AdminBlogRouteImport } from './routes/admin.blog'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as ApiPublicPaystackWebhookRouteImport } from './routes/api/public/paystack-webhook'
import { Route as AdminBlogIdRouteImport } from './routes/admin.blog.$id'
import { Route as ProfileIdItemKindItemIdRouteImport } from './routes/profile.$id.item.$kind.$itemId'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProfileIdRoute = ProfileIdRouteImport.update({
  id: '/profile/$id',
  path: '/profile/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentReturnRoute = PaymentReturnRouteImport.update({
  id: '/payment/return',
  path: '/payment/return',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderIdRoute = OrderIdRouteImport.update({
  id: '/order/$id',
  path: '/order/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutIdRoute = CheckoutIdRouteImport.update({
  id: '/checkout/$id',
  path: '/checkout/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSystemWalletsRoute = AdminSystemWalletsRouteImport.update({
  id: '/system-wallets',
  path: '/system-wallets',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPayoutsRoute = AdminPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFeaturesRoute = AdminFeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoursesRoute = AdminCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommunicationsRoute = AdminCommunicationsRouteImport.update({
  id: '/communications',
  path: '/communications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCampaignsRoute = AdminCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBountiesRoute = AdminBountiesRouteImport.update({
  id: '/bounties',
  path: '/bounties',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicPaystackWebhookRoute =
  ApiPublicPaystackWebhookRouteImport.update({
    id: '/api/public/paystack-webhook',
    path: '/api/public/paystack-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminBlogIdRoute = AdminBlogIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminBlogRoute,
} as any)
const ProfileIdItemKindItemIdRoute = ProfileIdItemKindItemIdRouteImport.update({
  id: '/item/$kind/$itemId',
  path: '/item/$kind/$itemId',
  getParentRoute: () => ProfileIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/audit': typeof AdminAuditRoute
  '/admin/blog': typeof AdminBlogRouteWithChildren
  '/admin/bounties': typeof AdminBountiesRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/communications': typeof AdminCommunicationsRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/features': typeof AdminFeaturesRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/system-wallets': typeof AdminSystemWalletsRoute
  '/admin/users': typeof AdminUsersRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/checkout/$id': typeof CheckoutIdRoute
  '/order/$id': typeof OrderIdRoute
  '/payment/return': typeof PaymentReturnRoute
  '/product/$id': typeof ProductIdRoute
  '/profile/$id': typeof ProfileIdRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
  '/profile/$id/item/$kind/$itemId': typeof ProfileIdItemKindItemIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/blog': typeof AdminBlogRouteWithChildren
  '/admin/bounties': typeof AdminBountiesRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/communications': typeof AdminCommunicationsRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/features': typeof AdminFeaturesRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/system-wallets': typeof AdminSystemWalletsRoute
  '/admin/users': typeof AdminUsersRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/checkout/$id': typeof CheckoutIdRoute
  '/order/$id': typeof OrderIdRoute
  '/payment/return': typeof PaymentReturnRoute
  '/product/$id': typeof ProductIdRoute
  '/profile/$id': typeof ProfileIdRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
  '/profile/$id/item/$kind/$itemId': typeof ProfileIdItemKindItemIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/audit': typeof AdminAuditRoute
  '/admin/blog': typeof AdminBlogRouteWithChildren
  '/admin/bounties': typeof AdminBountiesRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/communications': typeof AdminCommunicationsRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/features': typeof AdminFeaturesRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/system-wallets': typeof AdminSystemWalletsRoute
  '/admin/users': typeof AdminUsersRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/checkout/$id': typeof CheckoutIdRoute
  '/order/$id': typeof OrderIdRoute
  '/payment/return': typeof PaymentReturnRoute
  '/product/$id': typeof ProductIdRoute
  '/profile/$id': typeof ProfileIdRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
  '/profile/$id/item/$kind/$itemId': typeof ProfileIdItemKindItemIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/audit'
    | '/admin/blog'
    | '/admin/bounties'
    | '/admin/campaigns'
    | '/admin/categories'
    | '/admin/communications'
    | '/admin/courses'
    | '/admin/features'
    | '/admin/payouts'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/system-wallets'
    | '/admin/users'
    | '/blog/$slug'
    | '/checkout/$id'
    | '/order/$id'
    | '/payment/return'
    | '/product/$id'
    | '/profile/$id'
    | '/admin/'
    | '/blog/'
    | '/admin/blog/$id'
    | '/api/public/paystack-webhook'
    | '/profile/$id/item/$kind/$itemId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/audit'
    | '/admin/blog'
    | '/admin/bounties'
    | '/admin/campaigns'
    | '/admin/categories'
    | '/admin/communications'
    | '/admin/courses'
    | '/admin/features'
    | '/admin/payouts'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/system-wallets'
    | '/admin/users'
    | '/blog/$slug'
    | '/checkout/$id'
    | '/order/$id'
    | '/payment/return'
    | '/product/$id'
    | '/profile/$id'
    | '/admin'
    | '/blog'
    | '/admin/blog/$id'
    | '/api/public/paystack-webhook'
    | '/profile/$id/item/$kind/$itemId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/audit'
    | '/admin/blog'
    | '/admin/bounties'
    | '/admin/campaigns'
    | '/admin/categories'
    | '/admin/communications'
    | '/admin/courses'
    | '/admin/features'
    | '/admin/payouts'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/system-wallets'
    | '/admin/users'
    | '/blog/$slug'
    | '/checkout/$id'
    | '/order/$id'
    | '/payment/return'
    | '/product/$id'
    | '/profile/$id'
    | '/admin/'
    | '/blog/'
    | '/admin/blog/$id'
    | '/api/public/paystack-webhook'
    | '/profile/$id/item/$kind/$itemId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BlogSlugRoute: typeof BlogSlugRoute
  CheckoutIdRoute: typeof CheckoutIdRoute
  OrderIdRoute: typeof OrderIdRoute
  PaymentReturnRoute: typeof PaymentReturnRoute
  ProductIdRoute: typeof ProductIdRoute
  ProfileIdRoute: typeof ProfileIdRouteWithChildren
  BlogIndexRoute: typeof BlogIndexRoute
  ApiPublicPaystackWebhookRoute: typeof ApiPublicPaystackWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/profile/$id': {
      id: '/profile/$id'
      path: '/profile/$id'
      fullPath: '/profile/$id'
      preLoaderRoute: typeof ProfileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/return': {
      id: '/payment/return'
      path: '/payment/return'
      fullPath: '/payment/return'
      preLoaderRoute: typeof PaymentReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$id': {
      id: '/order/$id'
      path: '/order/$id'
      fullPath: '/order/$id'
      preLoaderRoute: typeof OrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$id': {
      id: '/checkout/$id'
      path: '/checkout/$id'
      fullPath: '/checkout/$id'
      preLoaderRoute: typeof CheckoutIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/system-wallets': {
      id: '/admin/system-wallets'
      path: '/system-wallets'
      fullPath: '/admin/system-wallets'
      preLoaderRoute: typeof AdminSystemWalletsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payouts': {
      id: '/admin/payouts'
      path: '/payouts'
      fullPath: '/admin/payouts'
      preLoaderRoute: typeof AdminPayoutsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/features': {
      id: '/admin/features'
      path: '/features'
      fullPath: '/admin/features'
      preLoaderRoute: typeof AdminFeaturesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/courses': {
      id: '/admin/courses'
      path: '/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AdminCoursesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/communications': {
      id: '/admin/communications'
      path: '/communications'
      fullPath: '/admin/communications'
      preLoaderRoute: typeof AdminCommunicationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/campaigns': {
      id: '/admin/campaigns'
      path: '/campaigns'
      fullPath: '/admin/campaigns'
      preLoaderRoute: typeof AdminCampaignsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bounties': {
      id: '/admin/bounties'
      path: '/bounties'
      fullPath: '/admin/bounties'
      preLoaderRoute: typeof AdminBountiesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/paystack-webhook': {
      id: '/api/public/paystack-webhook'
      path: '/api/public/paystack-webhook'
      fullPath: '/api/public/paystack-webhook'
      preLoaderRoute: typeof ApiPublicPaystackWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/blog/$id': {
      id: '/admin/blog/$id'
      path: '/$id'
      fullPath: '/admin/blog/$id'
      preLoaderRoute: typeof AdminBlogIdRouteImport
      parentRoute: typeof AdminBlogRoute
    }
    '/profile/$id/item/$kind/$itemId': {
      id: '/profile/$id/item/$kind/$itemId'
      path: '/item/$kind/$itemId'
      fullPath: '/profile/$id/item/$kind/$itemId'
      preLoaderRoute: typeof ProfileIdItemKindItemIdRouteImport
      parentRoute: typeof ProfileIdRoute
    }
  }
}

interface AdminBlogRouteChildren {
  AdminBlogIdRoute: typeof AdminBlogIdRoute
}

const AdminBlogRouteChildren: AdminBlogRouteChildren = {
  AdminBlogIdRoute: AdminBlogIdRoute,
}

const AdminBlogRouteWithChildren = AdminBlogRoute._addFileChildren(
  AdminBlogRouteChildren,
)

interface AdminRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminBlogRoute: typeof AdminBlogRouteWithChildren
  AdminBountiesRoute: typeof AdminBountiesRoute
  AdminCampaignsRoute: typeof AdminCampaignsRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminCommunicationsRoute: typeof AdminCommunicationsRoute
  AdminCoursesRoute: typeof AdminCoursesRoute
  AdminFeaturesRoute: typeof AdminFeaturesRoute
  AdminPayoutsRoute: typeof AdminPayoutsRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSystemWalletsRoute: typeof AdminSystemWalletsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminBlogRoute: AdminBlogRouteWithChildren,
  AdminBountiesRoute: AdminBountiesRoute,
  AdminCampaignsRoute: AdminCampaignsRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminCommunicationsRoute: AdminCommunicationsRoute,
  AdminCoursesRoute: AdminCoursesRoute,
  AdminFeaturesRoute: AdminFeaturesRoute,
  AdminPayoutsRoute: AdminPayoutsRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSystemWalletsRoute: AdminSystemWalletsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ProfileIdRouteChildren {
  ProfileIdItemKindItemIdRoute: typeof ProfileIdItemKindItemIdRoute
}

const ProfileIdRouteChildren: ProfileIdRouteChildren = {
  ProfileIdItemKindItemIdRoute: ProfileIdItemKindItemIdRoute,
}

const ProfileIdRouteWithChildren = ProfileIdRoute._addFileChildren(
  ProfileIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BlogSlugRoute: BlogSlugRoute,
  CheckoutIdRoute: CheckoutIdRoute,
  OrderIdRoute: OrderIdRoute,
  PaymentReturnRoute: PaymentReturnRoute,
  ProductIdRoute: ProductIdRoute,
  ProfileIdRoute: ProfileIdRouteWithChildren,
  BlogIndexRoute: BlogIndexRoute,
  ApiPublicPaystackWebhookRoute: ApiPublicPaystackWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
