/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ReportProblemRouteImport } from './routes/report-problem'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as HelpRouteImport } from './routes/help'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdvertiseRouteImport } from './routes/advertise'
import { Route as AdsManagerRouteImport } from './routes/ads-manager'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as WalletHistoryRouteImport } from './routes/wallet.history'
import { Route as ProfileIdRouteImport } from './routes/profile.$id'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as PaymentReturnRouteImport } from './routes/payment.return'
import { Route as OrderIdRouteImport } from './routes/order.$id'
import { Route as CheckoutIdRouteImport } from './routes/checkout.$id'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AdsManagerIdRouteImport } from './routes/ads-manager.$id'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSystemWalletsRouteImport } from './routes/admin.system-wallets'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminPayoutsRouteImport } from './routes/admin.payouts'
import { Route as AdminFeaturesRouteImport } from './routes/admin.features'
import { Route as AdminCoursesRouteImport } from './routes/admin.courses'
import { Route as AdminCommunicationsRouteImport } from './routes/admin.communications'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminCampaignsRouteImport } from './routes/admin.campaigns'
import { Route as AdminBountiesRouteImport } from './routes/admin.bounties'
import { Route as AdminBlogRouteImport } from './routes/admin.blog'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminAdInquiriesRouteImport } from './routes/admin.ad-inquiries'
import { Route as AdminBlogIndexRouteImport } from './routes/admin.blog.index'
import { Route as ApiPublicPaystackWebhookRouteImport } from './routes/api/public/paystack-webhook'
import { Route as AdminBlogIdRouteImport } from './routes/admin.blog.$id'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as ApiPublicPIdRouteImport } from './routes/api/public/p.$id'
import { Route as ApiPublicHooksPurgeDeletedAccountsRouteImport } from './routes/api/public/hooks/purge-deleted-accounts'
import { Route as ProfileIdItemKindItemIdRouteImport } from './routes/profile.$id.item.$kind.$itemId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportProblemRoute = ReportProblemRouteImport.update({
  id: '/report-problem',
  path: '/report-problem',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvertiseRoute = AdvertiseRouteImport.update({
  id: '/advertise',
  path: '/advertise',
  getParentRoute: () => rootRouteImport,
} as any)
const AdsManagerRoute = AdsManagerRouteImport.update({
  id: '/ads-manager',
  path: '/ads-manager',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const WalletHistoryRoute = WalletHistoryRouteImport.update({
  id: '/wallet/history',
  path: '/wallet/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIdRoute = ProfileIdRouteImport.update({
  id: '/profile/$id',
  path: '/profile/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentReturnRoute = PaymentReturnRouteImport.update({
  id: '/payment/return',
  path: '/payment/return',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderIdRoute = OrderIdRouteImport.update({
  id: '/order/$id',
  path: '/order/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutIdRoute = CheckoutIdRouteImport.update({
  id: '/checkout/$id',
  path: '/checkout/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdsManagerIdRoute = AdsManagerIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdsManagerRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSystemWalletsRoute = AdminSystemWalletsRouteImport.update({
  id: '/system-wallets',
  path: '/system-wallets',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPayoutsRoute = AdminPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFeaturesRoute = AdminFeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoursesRoute = AdminCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommunicationsRoute = AdminCommunicationsRouteImport.update({
  id: '/communications',
  path: '/communications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCampaignsRoute = AdminCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBountiesRoute = AdminBountiesRouteImport.update({
  id: '/bounties',
  path: '/bounties',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdInquiriesRoute = AdminAdInquiriesRouteImport.update({
  id: '/ad-inquiries',
  path: '/ad-inquiries',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogIndexRoute = AdminBlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminBlogRoute,
} as any)
const ApiPublicPaystackWebhookRoute =
  ApiPublicPaystackWebhookRouteImport.update({
    id: '/api/public/paystack-webhook',
    path: '/api/public/paystack-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminBlogIdRoute = AdminBlogIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminBlogRoute,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPIdRoute = ApiPublicPIdRouteImport.update({
  id: '/api/public/p/$id',
  path: '/api/public/p/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksPurgeDeletedAccountsRoute =
  ApiPublicHooksPurgeDeletedAccountsRouteImport.update({
    id: '/api/public/hooks/purge-deleted-accounts',
    path: '/api/public/hooks/purge-deleted-accounts',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProfileIdItemKindItemIdRoute = ProfileIdItemKindItemIdRouteImport.update({
  id: '/item/$kind/$itemId',
  path: '/item/$kind/$itemId',
  getParentRoute: () => ProfileIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/ads-manager': typeof AdsManagerRouteWithChildren
  '/advertise': typeof AdvertiseRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/help': typeof HelpRoute
  '/privacy': typeof PrivacyRoute
  '/report-problem': typeof ReportProblemRoute
  '/terms': typeof TermsRoute
  '/admin/ad-inquiries': typeof AdminAdInquiriesRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/blog': typeof AdminBlogRouteWithChildren
  '/admin/bounties': typeof AdminBountiesRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/communications': typeof AdminCommunicationsRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/features': typeof AdminFeaturesRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/system-wallets': typeof AdminSystemWalletsRoute
  '/admin/users': typeof AdminUsersRoute
  '/ads-manager/$id': typeof AdsManagerIdRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/checkout/$id': typeof CheckoutIdRoute
  '/order/$id': typeof OrderIdRoute
  '/payment/return': typeof PaymentReturnRoute
  '/product/$id': typeof ProductIdRoute
  '/profile/$id': typeof ProfileIdRouteWithChildren
  '/wallet/history': typeof WalletHistoryRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
  '/api/public/hooks/purge-deleted-accounts': typeof ApiPublicHooksPurgeDeletedAccountsRoute
  '/api/public/p/$id': typeof ApiPublicPIdRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/profile/$id/item/$kind/$itemId': typeof ProfileIdItemKindItemIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ads-manager': typeof AdsManagerRouteWithChildren
  '/advertise': typeof AdvertiseRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/help': typeof HelpRoute
  '/privacy': typeof PrivacyRoute
  '/report-problem': typeof ReportProblemRoute
  '/terms': typeof TermsRoute
  '/admin/ad-inquiries': typeof AdminAdInquiriesRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/bounties': typeof AdminBountiesRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/communications': typeof AdminCommunicationsRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/features': typeof AdminFeaturesRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/system-wallets': typeof AdminSystemWalletsRoute
  '/admin/users': typeof AdminUsersRoute
  '/ads-manager/$id': typeof AdsManagerIdRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/checkout/$id': typeof CheckoutIdRoute
  '/order/$id': typeof OrderIdRoute
  '/payment/return': typeof PaymentReturnRoute
  '/product/$id': typeof ProductIdRoute
  '/profile/$id': typeof ProfileIdRouteWithChildren
  '/wallet/history': typeof WalletHistoryRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
  '/admin/blog': typeof AdminBlogIndexRoute
  '/api/public/hooks/purge-deleted-accounts': typeof ApiPublicHooksPurgeDeletedAccountsRoute
  '/api/public/p/$id': typeof ApiPublicPIdRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/profile/$id/item/$kind/$itemId': typeof ProfileIdItemKindItemIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/ads-manager': typeof AdsManagerRouteWithChildren
  '/advertise': typeof AdvertiseRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/help': typeof HelpRoute
  '/privacy': typeof PrivacyRoute
  '/report-problem': typeof ReportProblemRoute
  '/terms': typeof TermsRoute
  '/admin/ad-inquiries': typeof AdminAdInquiriesRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/blog': typeof AdminBlogRouteWithChildren
  '/admin/bounties': typeof AdminBountiesRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/communications': typeof AdminCommunicationsRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/features': typeof AdminFeaturesRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/system-wallets': typeof AdminSystemWalletsRoute
  '/admin/users': typeof AdminUsersRoute
  '/ads-manager/$id': typeof AdsManagerIdRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/checkout/$id': typeof CheckoutIdRoute
  '/order/$id': typeof OrderIdRoute
  '/payment/return': typeof PaymentReturnRoute
  '/product/$id': typeof ProductIdRoute
  '/profile/$id': typeof ProfileIdRouteWithChildren
  '/wallet/history': typeof WalletHistoryRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
  '/api/public/hooks/purge-deleted-accounts': typeof ApiPublicHooksPurgeDeletedAccountsRoute
  '/api/public/p/$id': typeof ApiPublicPIdRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/profile/$id/item/$kind/$itemId': typeof ProfileIdItemKindItemIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/ads-manager'
    | '/advertise'
    | '/dashboard'
    | '/faq'
    | '/help'
    | '/privacy'
    | '/report-problem'
    | '/terms'
    | '/admin/ad-inquiries'
    | '/admin/audit'
    | '/admin/blog'
    | '/admin/bounties'
    | '/admin/campaigns'
    | '/admin/categories'
    | '/admin/communications'
    | '/admin/courses'
    | '/admin/features'
    | '/admin/payouts'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/system-wallets'
    | '/admin/users'
    | '/ads-manager/$id'
    | '/blog/$slug'
    | '/checkout/$id'
    | '/order/$id'
    | '/payment/return'
    | '/product/$id'
    | '/profile/$id'
    | '/wallet/history'
    | '/admin/'
    | '/blog/'
    | '/admin/blog/$id'
    | '/api/public/paystack-webhook'
    | '/admin/blog/'
    | '/api/public/hooks/purge-deleted-accounts'
    | '/api/public/p/$id'
    | '/lovable/email/queue/process'
    | '/profile/$id/item/$kind/$itemId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ads-manager'
    | '/advertise'
    | '/dashboard'
    | '/faq'
    | '/help'
    | '/privacy'
    | '/report-problem'
    | '/terms'
    | '/admin/ad-inquiries'
    | '/admin/audit'
    | '/admin/bounties'
    | '/admin/campaigns'
    | '/admin/categories'
    | '/admin/communications'
    | '/admin/courses'
    | '/admin/features'
    | '/admin/payouts'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/system-wallets'
    | '/admin/users'
    | '/ads-manager/$id'
    | '/blog/$slug'
    | '/checkout/$id'
    | '/order/$id'
    | '/payment/return'
    | '/product/$id'
    | '/profile/$id'
    | '/wallet/history'
    | '/admin'
    | '/blog'
    | '/admin/blog/$id'
    | '/api/public/paystack-webhook'
    | '/admin/blog'
    | '/api/public/hooks/purge-deleted-accounts'
    | '/api/public/p/$id'
    | '/lovable/email/queue/process'
    | '/profile/$id/item/$kind/$itemId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/ads-manager'
    | '/advertise'
    | '/dashboard'
    | '/faq'
    | '/help'
    | '/privacy'
    | '/report-problem'
    | '/terms'
    | '/admin/ad-inquiries'
    | '/admin/audit'
    | '/admin/blog'
    | '/admin/bounties'
    | '/admin/campaigns'
    | '/admin/categories'
    | '/admin/communications'
    | '/admin/courses'
    | '/admin/features'
    | '/admin/payouts'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/system-wallets'
    | '/admin/users'
    | '/ads-manager/$id'
    | '/blog/$slug'
    | '/checkout/$id'
    | '/order/$id'
    | '/payment/return'
    | '/product/$id'
    | '/profile/$id'
    | '/wallet/history'
    | '/admin/'
    | '/blog/'
    | '/admin/blog/$id'
    | '/api/public/paystack-webhook'
    | '/admin/blog/'
    | '/api/public/hooks/purge-deleted-accounts'
    | '/api/public/p/$id'
    | '/lovable/email/queue/process'
    | '/profile/$id/item/$kind/$itemId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdsManagerRoute: typeof AdsManagerRouteWithChildren
  AdvertiseRoute: typeof AdvertiseRoute
  DashboardRoute: typeof DashboardRoute
  FaqRoute: typeof FaqRoute
  HelpRoute: typeof HelpRoute
  PrivacyRoute: typeof PrivacyRoute
  ReportProblemRoute: typeof ReportProblemRoute
  TermsRoute: typeof TermsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CheckoutIdRoute: typeof CheckoutIdRoute
  OrderIdRoute: typeof OrderIdRoute
  PaymentReturnRoute: typeof PaymentReturnRoute
  ProductIdRoute: typeof ProductIdRoute
  ProfileIdRoute: typeof ProfileIdRouteWithChildren
  WalletHistoryRoute: typeof WalletHistoryRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ApiPublicPaystackWebhookRoute: typeof ApiPublicPaystackWebhookRoute
  ApiPublicHooksPurgeDeletedAccountsRoute: typeof ApiPublicHooksPurgeDeletedAccountsRoute
  ApiPublicPIdRoute: typeof ApiPublicPIdRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report-problem': {
      id: '/report-problem'
      path: '/report-problem'
      fullPath: '/report-problem'
      preLoaderRoute: typeof ReportProblemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advertise': {
      id: '/advertise'
      path: '/advertise'
      fullPath: '/advertise'
      preLoaderRoute: typeof AdvertiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ads-manager': {
      id: '/ads-manager'
      path: '/ads-manager'
      fullPath: '/ads-manager'
      preLoaderRoute: typeof AdsManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/wallet/history': {
      id: '/wallet/history'
      path: '/wallet/history'
      fullPath: '/wallet/history'
      preLoaderRoute: typeof WalletHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$id': {
      id: '/profile/$id'
      path: '/profile/$id'
      fullPath: '/profile/$id'
      preLoaderRoute: typeof ProfileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/return': {
      id: '/payment/return'
      path: '/payment/return'
      fullPath: '/payment/return'
      preLoaderRoute: typeof PaymentReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$id': {
      id: '/order/$id'
      path: '/order/$id'
      fullPath: '/order/$id'
      preLoaderRoute: typeof OrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$id': {
      id: '/checkout/$id'
      path: '/checkout/$id'
      fullPath: '/checkout/$id'
      preLoaderRoute: typeof CheckoutIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ads-manager/$id': {
      id: '/ads-manager/$id'
      path: '/$id'
      fullPath: '/ads-manager/$id'
      preLoaderRoute: typeof AdsManagerIdRouteImport
      parentRoute: typeof AdsManagerRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/system-wallets': {
      id: '/admin/system-wallets'
      path: '/system-wallets'
      fullPath: '/admin/system-wallets'
      preLoaderRoute: typeof AdminSystemWalletsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payouts': {
      id: '/admin/payouts'
      path: '/payouts'
      fullPath: '/admin/payouts'
      preLoaderRoute: typeof AdminPayoutsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/features': {
      id: '/admin/features'
      path: '/features'
      fullPath: '/admin/features'
      preLoaderRoute: typeof AdminFeaturesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/courses': {
      id: '/admin/courses'
      path: '/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AdminCoursesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/communications': {
      id: '/admin/communications'
      path: '/communications'
      fullPath: '/admin/communications'
      preLoaderRoute: typeof AdminCommunicationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/campaigns': {
      id: '/admin/campaigns'
      path: '/campaigns'
      fullPath: '/admin/campaigns'
      preLoaderRoute: typeof AdminCampaignsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bounties': {
      id: '/admin/bounties'
      path: '/bounties'
      fullPath: '/admin/bounties'
      preLoaderRoute: typeof AdminBountiesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ad-inquiries': {
      id: '/admin/ad-inquiries'
      path: '/ad-inquiries'
      fullPath: '/admin/ad-inquiries'
      preLoaderRoute: typeof AdminAdInquiriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog/': {
      id: '/admin/blog/'
      path: '/'
      fullPath: '/admin/blog/'
      preLoaderRoute: typeof AdminBlogIndexRouteImport
      parentRoute: typeof AdminBlogRoute
    }
    '/api/public/paystack-webhook': {
      id: '/api/public/paystack-webhook'
      path: '/api/public/paystack-webhook'
      fullPath: '/api/public/paystack-webhook'
      preLoaderRoute: typeof ApiPublicPaystackWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/blog/$id': {
      id: '/admin/blog/$id'
      path: '/$id'
      fullPath: '/admin/blog/$id'
      preLoaderRoute: typeof AdminBlogIdRouteImport
      parentRoute: typeof AdminBlogRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/p/$id': {
      id: '/api/public/p/$id'
      path: '/api/public/p/$id'
      fullPath: '/api/public/p/$id'
      preLoaderRoute: typeof ApiPublicPIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/purge-deleted-accounts': {
      id: '/api/public/hooks/purge-deleted-accounts'
      path: '/api/public/hooks/purge-deleted-accounts'
      fullPath: '/api/public/hooks/purge-deleted-accounts'
      preLoaderRoute: typeof ApiPublicHooksPurgeDeletedAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$id/item/$kind/$itemId': {
      id: '/profile/$id/item/$kind/$itemId'
      path: '/item/$kind/$itemId'
      fullPath: '/profile/$id/item/$kind/$itemId'
      preLoaderRoute: typeof ProfileIdItemKindItemIdRouteImport
      parentRoute: typeof ProfileIdRoute
    }
  }
}

interface AdminBlogRouteChildren {
  AdminBlogIdRoute: typeof AdminBlogIdRoute
  AdminBlogIndexRoute: typeof AdminBlogIndexRoute
}

const AdminBlogRouteChildren: AdminBlogRouteChildren = {
  AdminBlogIdRoute: AdminBlogIdRoute,
  AdminBlogIndexRoute: AdminBlogIndexRoute,
}

const AdminBlogRouteWithChildren = AdminBlogRoute._addFileChildren(
  AdminBlogRouteChildren,
)

interface AdminRouteChildren {
  AdminAdInquiriesRoute: typeof AdminAdInquiriesRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminBlogRoute: typeof AdminBlogRouteWithChildren
  AdminBountiesRoute: typeof AdminBountiesRoute
  AdminCampaignsRoute: typeof AdminCampaignsRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminCommunicationsRoute: typeof AdminCommunicationsRoute
  AdminCoursesRoute: typeof AdminCoursesRoute
  AdminFeaturesRoute: typeof AdminFeaturesRoute
  AdminPayoutsRoute: typeof AdminPayoutsRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSystemWalletsRoute: typeof AdminSystemWalletsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdInquiriesRoute: AdminAdInquiriesRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminBlogRoute: AdminBlogRouteWithChildren,
  AdminBountiesRoute: AdminBountiesRoute,
  AdminCampaignsRoute: AdminCampaignsRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminCommunicationsRoute: AdminCommunicationsRoute,
  AdminCoursesRoute: AdminCoursesRoute,
  AdminFeaturesRoute: AdminFeaturesRoute,
  AdminPayoutsRoute: AdminPayoutsRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSystemWalletsRoute: AdminSystemWalletsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AdsManagerRouteChildren {
  AdsManagerIdRoute: typeof AdsManagerIdRoute
}

const AdsManagerRouteChildren: AdsManagerRouteChildren = {
  AdsManagerIdRoute: AdsManagerIdRoute,
}

const AdsManagerRouteWithChildren = AdsManagerRoute._addFileChildren(
  AdsManagerRouteChildren,
)

interface ProfileIdRouteChildren {
  ProfileIdItemKindItemIdRoute: typeof ProfileIdItemKindItemIdRoute
}

const ProfileIdRouteChildren: ProfileIdRouteChildren = {
  ProfileIdItemKindItemIdRoute: ProfileIdItemKindItemIdRoute,
}

const ProfileIdRouteWithChildren = ProfileIdRoute._addFileChildren(
  ProfileIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AdsManagerRoute: AdsManagerRouteWithChildren,
  AdvertiseRoute: AdvertiseRoute,
  DashboardRoute: DashboardRoute,
  FaqRoute: FaqRoute,
  HelpRoute: HelpRoute,
  PrivacyRoute: PrivacyRoute,
  ReportProblemRoute: ReportProblemRoute,
  TermsRoute: TermsRoute,
  BlogSlugRoute: BlogSlugRoute,
  CheckoutIdRoute: CheckoutIdRoute,
  OrderIdRoute: OrderIdRoute,
  PaymentReturnRoute: PaymentReturnRoute,
  ProductIdRoute: ProductIdRoute,
  ProfileIdRoute: ProfileIdRouteWithChildren,
  WalletHistoryRoute: WalletHistoryRoute,
  BlogIndexRoute: BlogIndexRoute,
  ApiPublicPaystackWebhookRoute: ApiPublicPaystackWebhookRoute,
  ApiPublicHooksPurgeDeletedAccountsRoute:
    ApiPublicHooksPurgeDeletedAccountsRoute,
  ApiPublicPIdRoute: ApiPublicPIdRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
