/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileIdRouteImport } from './routes/profile.$id'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as ProfileIdItemKindItemIdRouteImport } from './routes/profile.$id.item.$kind.$itemId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIdRoute = ProfileIdRouteImport.update({
  id: '/profile/$id',
  path: '/profile/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIdItemKindItemIdRoute = ProfileIdItemKindItemIdRouteImport.update({
  id: '/item/$kind/$itemId',
  path: '/item/$kind/$itemId',
  getParentRoute: () => ProfileIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/reports': typeof AdminReportsRoute
  '/product/$id': typeof ProductIdRoute
  '/profile/$id': typeof ProfileIdRouteWithChildren
  '/profile/$id/item/$kind/$itemId': typeof ProfileIdItemKindItemIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/reports': typeof AdminReportsRoute
  '/product/$id': typeof ProductIdRoute
  '/profile/$id': typeof ProfileIdRouteWithChildren
  '/profile/$id/item/$kind/$itemId': typeof ProfileIdItemKindItemIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/reports': typeof AdminReportsRoute
  '/product/$id': typeof ProductIdRoute
  '/profile/$id': typeof ProfileIdRouteWithChildren
  '/profile/$id/item/$kind/$itemId': typeof ProfileIdItemKindItemIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/reports'
    | '/product/$id'
    | '/profile/$id'
    | '/profile/$id/item/$kind/$itemId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/reports'
    | '/product/$id'
    | '/profile/$id'
    | '/profile/$id/item/$kind/$itemId'
  id:
    | '__root__'
    | '/'
    | '/admin/reports'
    | '/product/$id'
    | '/profile/$id'
    | '/profile/$id/item/$kind/$itemId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminReportsRoute: typeof AdminReportsRoute
  ProductIdRoute: typeof ProductIdRoute
  ProfileIdRoute: typeof ProfileIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$id': {
      id: '/profile/$id'
      path: '/profile/$id'
      fullPath: '/profile/$id'
      preLoaderRoute: typeof ProfileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$id/item/$kind/$itemId': {
      id: '/profile/$id/item/$kind/$itemId'
      path: '/item/$kind/$itemId'
      fullPath: '/profile/$id/item/$kind/$itemId'
      preLoaderRoute: typeof ProfileIdItemKindItemIdRouteImport
      parentRoute: typeof ProfileIdRoute
    }
  }
}

interface ProfileIdRouteChildren {
  ProfileIdItemKindItemIdRoute: typeof ProfileIdItemKindItemIdRoute
}

const ProfileIdRouteChildren: ProfileIdRouteChildren = {
  ProfileIdItemKindItemIdRoute: ProfileIdItemKindItemIdRoute,
}

const ProfileIdRouteWithChildren = ProfileIdRoute._addFileChildren(
  ProfileIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminReportsRoute: AdminReportsRoute,
  ProductIdRoute: ProductIdRoute,
  ProfileIdRoute: ProfileIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
